version: 0.0

os: linix

files:
  # Unzip the build artifacts in ~/app
  - source: /
    destination: /home/ec2-user/app/release

permissions:
  # Change permissions from root to ec2-user
  - object: /home/ec2-user/app/release
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    # Start the app
    - location: start-service.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    # Stop the app
    - location: stop-service.sh
      timeout: 300
      runas: ec2-user
