version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      # run `npm install`
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - server.js
    - package.json
    - appspec.yaml
    - 'node_modules/**/*'
